/* ============================================================
   dados-demo.js — DADOS DE TESTE (não carregado pelo app)

   São os 14 tickets fictícios e as 8 avaliações de demonstração
   que existiam antes. Ficaram guardados aqui só para referência.
   Para voltar a usá-los, inclua este arquivo no index.html ANTES
   de dados.js e apague as listas vazias de lá.
   ============================================================ */

/** Lista achatada de critérios, na ordem de exibição. */
const CRITERIOS = GRUPOS_CRITERIOS.flatMap((g) => g.criterios);

/* ============================== TICKETS ============================== */
/* de: 'cliente' | 'atendente' | 'ia' | 'nota' (nota interna do sistema)   */

const TICKETS = [
  {
    id: 'TCK-1042',
    loja: 'Casa Fontana',
    contato: 'Eduardo Oliveira',
    atendente: 'murilo',
    canal: 'Web',
    assunto: 'Cliente não consegue reservar para setembro',
    tags: ['Reservas', 'Configuração'],
    abertoEm: '2026-08-03T16:22:00',
    primeiraRespostaMin: 4,
    duracaoMin: 206,
    contextoSugerido: 'churn',
    mensagens: [
      { de: 'cliente', autor: 'Eduardo Oliveira', hora: '16:22', texto: 'Boa tarde. Meus clientes estão reclamando que não conseguem reservar para setembro. O link só mostra até 03/09 e depois fica tudo cinza. Isso já me fez perder duas festas de aniversário essa semana.' },
      { de: 'ia', autor: 'IA', hora: '16:33', texto: 'A causa mais comum quando o cliente não consegue reservar para um mês à frente é a configuração de "Dias de antecedência" nas Configurações Avançadas de Reserva.\n\nEsse campo define o máximo de dias no futuro que o cliente pode reservar. Se está em 30 dias, hoje (03/08) ele só consegue reservar até 03/09.' },
      { de: 'ia', autor: 'IA', hora: '16:33', texto: 'Como resolver:\n1. Vá em Reservas → Áreas e Mesas\n2. Clique em Configurações Avançadas (no topo da tela)\n3. Aumente o campo "Dias de antecedência" para cobrir setembro (ex.: 60 dias)\n4. Clique em Salvar\n\nIsso deve liberar as datas de setembro. Quer tentar aí? 🙂' },
      { de: 'cliente', autor: 'Eduardo Oliveira', hora: '18:40', texto: 'Fiz isso e continua igual. Já estou começando a achar que essa ferramenta não é pra mim, sinceramente.' },
      { de: 'atendente', autor: 'Murilo', hora: '19:48', texto: 'Boa tarde, Eduardo! Aqui é o Murilo, assumi seu atendimento. Antes de te pedir qualquer coisa, fui olhar a sua conta.' },
      { de: 'atendente', autor: 'Murilo', hora: '19:52', texto: 'Achei o problema: a antecedência já estava em 60 dias, mas a área "Salão Principal" tem um período de bloqueio ativo de 01/09 a 30/09 que alguém criou em julho. Era esse bloqueio que estava deixando setembro todo cinza, não a antecedência.' },
      { de: 'atendente', autor: 'Murilo', hora: '19:53', texto: 'Removi o bloqueio agora e testei o seu link de reserva: consegui simular uma reserva para 12/09 às 20h, mesa para 6. Pode conferir?' },
      { de: 'cliente', autor: 'Eduardo Oliveira', hora: '19:58', texto: 'Testei aqui e agora abriu setembro todo. Era isso mesmo! Obrigado pela agilidade.' },
      { de: 'atendente', autor: 'Murilo', hora: '20:02', texto: 'Que bom! Duas coisas pra não acontecer de novo: (1) deixei uma anotação na sua conta sobre esse bloqueio, e (2) recomendo que só o seu usuário admin tenha permissão de criar bloqueios de período — hoje os 4 usuários da equipe podem. Se quiser, ajusto isso pra você em 2 minutos.\n\nE sobre as duas festas que você perdeu: já sinalizei internamente pro seu gerente de conta te chamar amanhã.' },
      { de: 'cliente', autor: 'Eduardo Oliveira', hora: '20:05', texto: 'Ajusta sim, por favor. E obrigado por olhar antes de me mandar mexer em tudo de novo.' },
    ],
  },

  {
    id: 'TCK-1039',
    loja: 'Vila Paraíso',
    contato: 'Bianca Ferraz (Marketing)',
    atendente: 'vitoria',
    canal: 'WhatsApp',
    assunto: 'Como colocar o cardápio digital no Instagram',
    tags: ['Cardápio', 'Onboarding'],
    abertoEm: '2026-08-04T09:12:00',
    primeiraRespostaMin: 6,
    duracaoMin: 41,
    contextoSugerido: 'onboarding',
    mensagens: [
      { de: 'cliente', autor: 'Marketing Vila Paraíso', hora: '09:12', texto: 'Oi! Somos novos aqui (entramos semana passada). Queria colocar o cardápio digital no link da bio do Instagram, mas não sei qual link usar. Tem um monte de link diferente no painel 😅' },
      { de: 'atendente', autor: 'Victoria', hora: '09:18', texto: 'Olá! 💜 Sou a Victoria, da Dionísio. Bem-vindos! Pergunta ótima — e você tem razão, tem mais de um link e eles servem pra coisas diferentes. Deixa eu te explicar rapidinho:' },
      { de: 'atendente', autor: 'Victoria', hora: '09:19', texto: '• Link do Cardápio → só o menu, sem pedido. Bom pra quem quer só olhar.\n• Link de Pedido → cardápio + carrinho (delivery/retirada).\n• Link de Reserva → agenda de mesas.\n\nPra bio do Instagram, o que costuma converter melhor é o Link de Pedido, porque ele já mostra o cardápio e permite fechar na hora.' },
      { de: 'atendente', autor: 'Victoria', hora: '09:21', texto: 'Onde pegar: Configuração → Links e QR Code → copiar "Link de Pedido".\nO seu já está pronto: vilaparaiso.dionisio.app/pedido' },
      { de: 'cliente', autor: 'Marketing Vila Paraíso', hora: '09:27', texto: 'Perfeito, coloquei! Só uma coisa: se eu quiser divulgar um prato específico no story, tem link direto do prato?' },
      { de: 'atendente', autor: 'Victoria', hora: '09:31', texto: 'Tem! No cardápio, clique nos três pontinhos do prato → "Copiar link do item". Ele abre o cardápio já com o prato aberto — funciona muito bem em story com figurinha de link.' },
      { de: 'atendente', autor: 'Victoria', hora: '09:33', texto: 'Já que vocês estão começando: na sexta às 15h tem o treinamento ao vivo de Cardápio + Pedidos (30 min, com espaço pra perguntas). Quer que eu te inscreva? E te mando também o QR Code do cardápio em PDF pra imprimir nas mesas, se fizer sentido.' },
      { de: 'cliente', autor: 'Marketing Vila Paraíso', hora: '09:44', texto: 'Quero as duas coisas! De nada, Victoria 😊 fico feliz em ter a ajuda de vocês.' },
      { de: 'atendente', autor: 'Victoria', hora: '09:53', texto: 'Inscrita ✅ e o PDF do QR Code está no seu e-mail. Qualquer coisa me chama por aqui!' },
    ],
  },

  {
    id: 'TCK-1036',
    loja: 'Empório de Comidas',
    contato: 'Sandra Nakagawa',
    atendente: 'ryan',
    canal: 'WhatsApp',
    assunto: 'Pedidos entrando duplicados no PDV',
    tags: ['Pedidos', 'Integração'],
    abertoEm: '2026-07-28T11:05:00',
    primeiraRespostaMin: 12,
    duracaoMin: 95,
    contextoSugerido: 'bug',
    mensagens: [
      { de: 'cliente', autor: 'Sandra', hora: '11:05', texto: 'Bom dia. Desde ontem todo pedido do delivery entra DUAS vezes no PDV. Ontem à noite a cozinha produziu 7 pratos a mais. Preciso disso resolvido hoje.' },
      { de: 'atendente', autor: 'Ryan', hora: '11:17', texto: 'Bom dia, Sandra! Siga exatamente esses passos: 1) saia do PDV, 2) limpe o cache do navegador, 3) entre de novo. Isso normalmente resolve duplicidade.' },
      { de: 'cliente', autor: 'Sandra', hora: '11:26', texto: 'Fiz, continua duplicando. Acabou de entrar outro duplicado agora (pedido #4471 e #4472, mesmo cliente, mesma hora).' },
      { de: 'atendente', autor: 'Ryan', hora: '11:34', texto: 'Estranho. Tenta desinstalar e instalar o app do PDV de novo?' },
      { de: 'cliente', autor: 'Sandra', hora: '11:41', texto: 'Gente, eu tenho um restaurante pra tocar. Não posso ficar reinstalando coisa no chute. Alguém aí pode OLHAR o que está acontecendo?' },
      { de: 'atendente', autor: 'Ryan', hora: '12:02', texto: 'Desculpa, Sandra. Vou olhar o log agora.' },
      { de: 'atendente', autor: 'Ryan', hora: '12:20', texto: 'Achei: sua loja está com dois webhooks apontando pro mesmo endpoint do PDV (um criado em 12/03 e um em 27/07). Cada pedido dispara os dois. Removi o webhook duplicado de 27/07.' },
      { de: 'cliente', autor: 'Sandra', hora: '12:31', texto: 'Entrou um pedido agora e veio só uma vez. Resolvido.' },
      { de: 'atendente', autor: 'Ryan', hora: '12:33', texto: 'Isso! Qualquer coisa chama.' },
      { de: 'nota', autor: 'Sistema', hora: '12:40', texto: 'Ticket fechado sem confirmar a causa do webhook duplicado com o time técnico. Nenhum acompanhamento foi agendado.' },
    ],
  },

  {
    id: 'TCK-1044',
    loja: 'Také Japanese Food',
    contato: 'Myung Lee',
    atendente: 'vitoria',
    canal: 'WhatsApp',
    assunto: 'Cobrança de R$ 149 que o cliente não reconhece',
    tags: ['Financeiro', 'Plano'],
    abertoEm: '2026-08-04T14:31:00',
    primeiraRespostaMin: 9,
    duracaoMin: 63,
    contextoSugerido: 'financeiro',
    mensagens: [
      { de: 'cliente', autor: 'Myung Lee', hora: '14:31', texto: 'Vi uma cobrança de R$ 149 no cartão hoje além da mensalidade de R$ 299. Não reconheço. O que é isso?' },
      { de: 'atendente', autor: 'Victoria', hora: '14:40', texto: 'Oi Myung, tudo bem? Deixa eu conferir sua fatura antes de te responder qualquer coisa — só um minutinho.' },
      { de: 'atendente', autor: 'Victoria', hora: '14:47', texto: 'Confirmado: os R$ 149 são do módulo de Cardápio Digital + QR Code, ativado no dia 22/07 pelo usuário andre@exemplo.com.br. Ele entra como item separado na fatura, por isso apareceu como cobrança extra.' },
      { de: 'cliente', autor: 'Myung Lee', hora: '14:52', texto: 'Ah, o André ativou por conta dele. A gente nem usou ainda. Consigo cancelar e ser reembolsado?' },
      { de: 'atendente', autor: 'Victoria', hora: '14:58', texto: 'Consegue sim. Como a ativação foi há 13 dias e o uso está em 0 (confirmei no relatório: nenhum acesso ao cardápio digital), você está dentro da política de reembolso integral de 15 dias.\n\nPosso desativar o módulo e solicitar o estorno dos R$ 149 agora. O estorno leva de 5 a 10 dias úteis pra aparecer na fatura do cartão, dependendo do banco.' },
      { de: 'cliente', autor: 'Myung Lee', hora: '15:01', texto: 'Isso, por favor.' },
      { de: 'atendente', autor: 'Victoria', hora: '15:14', texto: 'Feito ✅ Módulo desativado e estorno protocolado (protocolo #EST-7781). Você vai receber um e-mail de confirmação em alguns minutos.\n\nDuas coisas úteis: (1) posso restringir a ativação de módulos pagos só para usuários admin, pra não acontecer sem você saber; (2) se em algum momento quiserem testar o cardápio digital de verdade, dá pra ligar 14 dias grátis — aí você decide com dado na mão.' },
      { de: 'cliente', autor: 'Myung Lee', hora: '15:19', texto: 'Restringe sim. E vou pensar no teste, obrigado pela transparência.' },
      { de: 'atendente', autor: 'Victoria', hora: '15:34', texto: 'Restrição aplicada. Bom atendimento hoje aí! 🍣' },
    ],
  },

  {
    id: 'TCK-1030',
    loja: 'Boss Steakhouse',
    contato: 'Ricardo Bessa',
    atendente: 'murilo',
    canal: 'WhatsApp',
    assunto: 'Reserva confirmada não apareceu para o restaurante',
    tags: ['Reservas', 'Incidente'],
    abertoEm: '2026-07-24T20:14:00',
    primeiraRespostaMin: 31,
    duracaoMin: 128,
    contextoSugerido: 'irritado',
    mensagens: [
      { de: 'cliente', autor: 'Ricardo Bessa', hora: '20:14', texto: 'Chegou uma família de 8 pessoas aqui agora com print da reserva confirmada pelo sistema de VOCÊS e no meu painel não tem nada. Passei vergonha na frente do cliente. Isso é inaceitável.' },
      { de: 'atendente', autor: 'Murilo', hora: '20:45', texto: 'Sr. Ricardo, boa noite. Entendo perfeitamente o incômodo, é constrangedor mesmo. Vou olhar isso agora com prioridade. Pode me passar o nome da reserva ou o telefone do cliente?' },
      { de: 'cliente', autor: 'Ricardo Bessa', hora: '20:47', texto: 'Família Aguiar, 8 pessoas, 20h. Telefone (11) 9xxxx-4412.' },
      { de: 'atendente', autor: 'Murilo', hora: '20:56', texto: 'Encontrei. A reserva EXISTE no sistema (código RSV-88214, criada 21/07 às 15:32), mas foi lançada na área "Deck Externo" — e o Deck está com visualização desativada no seu painel desde 19/07, quando vocês tiraram o deck de operação pela chuva. Por isso ela não aparecia na sua lista.' },
      { de: 'atendente', autor: 'Murilo', hora: '20:58', texto: 'Ou seja: não foi perda de dado, foi visibilidade. Já reativei a exibição da área e a reserva apareceu na sua tela — pode conferir. E o cliente conseguiu ser acomodado?' },
      { de: 'cliente', autor: 'Ricardo Bessa', hora: '21:04', texto: 'Conseguimos encaixar em duas mesas juntas, mas não é o ponto. Se o deck estava fora, por que o sistema continuou aceitando reserva pra lá?' },
      { de: 'atendente', autor: 'Murilo', hora: '21:12', texto: 'Pergunta certíssima, e a resposta é desconfortável: desativar a exibição da área no painel não bloqueia o recebimento de reservas pra ela — são dois controles separados (Exibição x Disponibilidade). Isso não está claro na interface e é uma falha nossa de produto, não sua.\n\nAbri o report interno #PRD-2231 com o time de produto anexando o seu caso.' },
      { de: 'atendente', autor: 'Murilo', hora: '21:15', texto: 'O que eu já fiz agora pra te proteger: coloquei o Deck Externo como indisponível de verdade (bloqueio de disponibilidade) até vocês reabrirem, e conferi se tem outra reserva futura presa nele — tem uma: 27/07, 21h, 4 pessoas, Sr. Douglas. Quer que eu remaneje pro salão e avise o cliente, ou vocês preferem falar com ele?' },
      { de: 'cliente', autor: 'Ricardo Bessa', hora: '21:22', texto: 'Remaneja e avisa vocês mesmos. E me manda por escrito esse negócio dos dois controles, quero passar pra minha equipe.' },
      { de: 'atendente', autor: 'Murilo', hora: '22:20', texto: 'Remanejado e cliente avisado por WhatsApp (ele confirmou). Te mandei por e-mail um resumo de 1 página: diferença entre Exibição e Disponibilidade, como bloquear área corretamente e o passo a passo pra sua equipe.\n\nDe novo, desculpa pelo constrangimento de hoje. Vou acompanhar o #PRD-2231 e te aviso quando mudar.' },
    ],
  },

  {
    id: 'TCK-1027',
    loja: 'Mundo Animal · Atibaia',
    contato: 'Mateus H. de Azevedo Leite',
    atendente: 'ryan',
    canal: 'Web',
    assunto: 'Relatório de vendas mostra número diferente do PDV',
    tags: ['Relatórios', 'Dados'],
    abertoEm: '2026-07-21T10:02:00',
    primeiraRespostaMin: 18,
    duracaoMin: 74,
    contextoSugerido: 'bug',
    mensagens: [
      { de: 'cliente', autor: 'Mateus', hora: '10:02', texto: 'O relatório de vendas do mês fechou em R$ 41.280 e meu PDV mostra R$ 43.910. Diferença de R$ 2.630. Qual dos dois está certo?' },
      { de: 'atendente', autor: 'Ryan', hora: '10:20', texto: 'Bom dia, Mateus! Provavelmente é diferença de fuso ou de horário de fechamento. O relatório considera o dia até 23:59.' },
      { de: 'cliente', autor: 'Mateus', hora: '10:24', texto: 'Mas eu fecho às 2h da manhã. Isso explicaria tudo?' },
      { de: 'atendente', autor: 'Ryan', hora: '10:29', texto: 'Deve ser isso sim. Nesse caso o relatório joga as vendas depois da meia-noite pro dia seguinte.' },
      { de: 'cliente', autor: 'Mateus', hora: '10:36', texto: 'Ok, mas isso não fecharia o mês? Se joga pro dia seguinte, no total do mês daria igual. A diferença continua.' },
      { de: 'atendente', autor: 'Ryan', hora: '10:52', texto: 'Verdade, faz sentido. Vou pedir pro time técnico olhar e te aviso.' },
      { de: 'cliente', autor: 'Mateus', hora: '11:10', texto: 'Beleza, aguardo. Preciso disso pra fechar com a contabilidade até quinta.' },
      { de: 'atendente', autor: 'Ryan', hora: '11:16', texto: 'Combinado, te retorno.' },
      { de: 'nota', autor: 'Sistema', hora: '11:16', texto: 'Nenhum chamado técnico foi aberto. Cliente reabriu o ticket em 23/07 cobrando retorno.' },
    ],
  },

  {
    id: 'TCK-1021',
    loja: 'Nakombi Express',
    contato: 'Camila Reis',
    atendente: 'vitoria',
    canal: 'WhatsApp',
    assunto: 'Quer cancelar: "não estou usando nem metade"',
    tags: ['Churn', 'Plano'],
    abertoEm: '2026-07-17T15:40:00',
    primeiraRespostaMin: 7,
    duracaoMin: 112,
    contextoSugerido: 'churn',
    mensagens: [
      { de: 'cliente', autor: 'Camila', hora: '15:40', texto: 'Oi, boa tarde. Quero cancelar. Pago R$ 499 e não uso nem metade do que tem aí. Não faz sentido pra mim.' },
      { de: 'atendente', autor: 'Victoria', hora: '15:47', texto: 'Oi Camila! Antes de tudo: obrigada por ser direta, isso me ajuda a te ajudar de verdade. Posso te fazer duas perguntas rápidas antes de encaminhar o cancelamento?' },
      { de: 'cliente', autor: 'Camila', hora: '15:49', texto: 'Pode.' },
      { de: 'atendente', autor: 'Victoria', hora: '15:52', texto: '1) Do que vocês usam hoje, o que realmente entrou na rotina?\n2) Teve alguma coisa que vocês tentaram usar e travou?\n\nPerguntei porque olhei sua conta aqui: reservas vocês usam todo dia (412 no mês), mas cardápio digital, pedidos e campanhas estão praticamente zerados. Se for esse o caso, você está pagando por um plano que não é o seu.' },
      { de: 'cliente', autor: 'Camila', hora: '16:03', texto: 'É exatamente isso. Usamos reserva e só. Tentamos o delivery em maio e foi confuso, desistimos.' },
      { de: 'atendente', autor: 'Victoria', hora: '16:11', texto: 'Então tenho duas saídas honestas pra te apresentar:\n\nA) Plano Reservas — R$ 249/mês. Mantém tudo que vocês usam hoje (reservas ilimitadas, lista de espera, confirmação automática), sem os módulos parados. Economia de R$ 250/mês, o histórico fica todo.\n\nB) Cancelamento — encaminho hoje, seus dados ficam exportáveis por 90 dias.\n\nEu não vou insistir na A se ela não fizer sentido. Só não queria você cancelando por causa de preço de coisa que você não pediu.' },
      { de: 'cliente', autor: 'Camila', hora: '16:22', texto: 'A opção A resolve. Por que ninguém me ofereceu isso antes?' },
      { de: 'atendente', autor: 'Victoria', hora: '16:28', texto: 'Pergunta justa — e a resposta é que a gente deveria ter olhado seu uso antes de você precisar pedir cancelamento. Vou registrar isso como aprendizado com o time.\n\nMigração feita ✅ Já vale no próximo ciclo (12/08), com crédito proporcional dos R$ 250 deste mês. Nada muda na sua operação hoje.' },
      { de: 'atendente', autor: 'Victoria', hora: '16:32', texto: 'E sobre o delivery ter sido confuso em maio: não vou te empurrar de volta agora. Mas se em algum momento vocês quiserem tentar, eu faço a configuração com você em 20 min de call, sem custo. Fica em aberto.' },
      { de: 'cliente', autor: 'Camila', hora: '16:35', texto: 'Combinado. Obrigada por não me enrolar, Victoria.' },
    ],
  },

  {
    id: 'TCK-1018',
    loja: 'Cantina do Zé',
    contato: 'José Barreto',
    atendente: 'murilo',
    canal: 'Web',
    assunto: 'Notificação de reserva não chega no WhatsApp do cliente',
    tags: ['Notificações', 'Reservas'],
    abertoEm: '2026-07-14T08:55:00',
    primeiraRespostaMin: 11,
    duracaoMin: 58,
    contextoSugerido: 'rotina',
    mensagens: [
      { de: 'cliente', autor: 'José', hora: '08:55', texto: 'Bom dia. Os clientes falam que não recebem a confirmação de reserva no WhatsApp. Chega e-mail, WhatsApp não.' },
      { de: 'atendente', autor: 'Murilo', hora: '09:06', texto: 'Bom dia, José! Já fui olhar sua configuração de notificações. Achei o motivo: o canal WhatsApp está ativo, mas o template "Confirmação de reserva" está com status Pendente de aprovação desde 09/07 — ele foi editado e voltou pra revisão da Meta. Enquanto está pendente, o sistema cai pro e-mail.' },
      { de: 'cliente', autor: 'José', hora: '09:12', texto: 'E quanto tempo demora essa aprovação?' },
      { de: 'atendente', autor: 'Murilo', hora: '09:18', texto: 'Normalmente de 1 a 24h, mas o seu está travado há 5 dias — o texto tem "confirme AGORA" em caixa alta, que costuma ser reprovado por parecer urgência forçada.\n\nDuas opções:\n1) Eu reverto pro template padrão aprovado (volta a funcionar hoje mesmo);\n2) Você ajusta o texto e submete de novo (mais 1–24h de espera).' },
      { de: 'cliente', autor: 'José', hora: '09:23', texto: 'Reverte pro padrão, preciso funcionando pro fim de semana.' },
      { de: 'atendente', autor: 'Murilo', hora: '09:31', texto: 'Revertido ✅ Fiz um teste real: criei uma reserva de teste no seu nome e a confirmação chegou no WhatsApp em 6 segundos. Já apaguei a reserva de teste.\n\nSe quiser personalizar o texto depois, me chama antes de submeter — eu reviso pra não cair na regra da Meta de novo.' },
      { de: 'cliente', autor: 'José', hora: '09:53', texto: 'Chegou aqui também. Valeu!' },
    ],
  },

  /* ---------------- pendentes de avaliação ---------------- */

  {
    id: 'TCK-1051',
    loja: 'Padaria Aurora',
    contato: 'Helena Sampaio',
    atendente: 'vitoria',
    canal: 'WhatsApp',
    assunto: 'Impressora de cozinha parou de imprimir pedidos',
    tags: ['Pedidos', 'Hardware'],
    abertoEm: '2026-08-05T07:41:00',
    primeiraRespostaMin: 5,
    duracaoMin: 47,
    contextoSugerido: 'bug',
    mensagens: [
      { de: 'cliente', autor: 'Helena', hora: '07:41', texto: 'Bom dia! Socorro: a impressora da cozinha parou de imprimir os pedidos hoje. Está tudo ligado, o pedido aparece na tela mas não sai o papel. Abrimos em 30 min.' },
      { de: 'atendente', autor: 'Victoria', hora: '07:46', texto: 'Bom dia, Helena! Vamos resolver antes de abrir. Antes de mexer em nada, deixa eu ver o status do seu agente de impressão daqui.' },
      { de: 'atendente', autor: 'Victoria', hora: '07:51', texto: 'Achei: o agente de impressão da sua loja está offline desde ontem 22:14 — ele roda no computador do caixa. Provavelmente o PC foi reiniciado no fechamento e o agente não subiu junto.\n\nNo PC do caixa, procure o ícone roxo "Dionísio Print" na bandeja do Windows (perto do relógio). Está lá?' },
      { de: 'cliente', autor: 'Helena', hora: '07:55', texto: 'Não tem o ícone. Só o navegador aberto.' },
      { de: 'atendente', autor: 'Victoria', hora: '07:57', texto: 'É isso então. Abra o Menu Iniciar, digite "Dionísio Print" e abra o programa. Ele vai aparecer na bandeja e ficar verde em uns 10 segundos.' },
      { de: 'cliente', autor: 'Helena', hora: '08:04', texto: 'Abri! Ficou verde. Mandei um pedido de teste e imprimiu 🙏' },
      { de: 'atendente', autor: 'Victoria', hora: '08:09', texto: 'Perfeito! Pra não repetir amanhã: dá pra deixar o Dionísio Print abrindo junto com o Windows. São 3 cliques e eu te guio agora, leva 1 minuto — quer fazer?' },
      { de: 'cliente', autor: 'Helena', hora: '08:11', texto: 'Quero!' },
      { de: 'atendente', autor: 'Victoria', hora: '08:12', texto: 'No ícone do Dionísio Print → botão direito → Configurações → marque "Iniciar com o Windows" → Salvar. Pronto, agora ele sobe sozinho. Boa abertura! 🥐' },
      { de: 'cliente', autor: 'Helena', hora: '08:28', texto: 'Marcado. Obrigada pela rapidez, vocês salvaram a manhã!' },
    ],
  },

  {
    id: 'TCK-1050',
    loja: 'Bar do Alto',
    contato: 'Thiago Menezes',
    atendente: 'ryan',
    canal: 'Web',
    assunto: 'Cliente pediu 2 vezes o mesmo relatório e não recebeu',
    tags: ['Relatórios', 'Reabertura'],
    abertoEm: '2026-08-04T17:03:00',
    primeiraRespostaMin: 22,
    duracaoMin: 39,
    contextoSugerido: 'irritado',
    mensagens: [
      { de: 'cliente', autor: 'Thiago', hora: '17:03', texto: 'É a terceira vez que peço o relatório de consumo por mesa de julho. Pedi dia 28, pedi dia 31, ninguém mandou. Vocês respondem "vamos verificar" e morre ali.' },
      { de: 'atendente', autor: 'Ryan', hora: '17:25', texto: 'Oi Thiago! Desculpa a demora. Você consegue exportar isso sozinho em Relatórios → Consumo → Exportar CSV.' },
      { de: 'cliente', autor: 'Thiago', hora: '17:28', texto: 'Eu SEI onde exporta. O problema é que o CSV vem sem a coluna de mesa, que é justamente o que eu preciso. Foi isso que eu expliquei nas duas vezes anteriores.' },
      { de: 'atendente', autor: 'Ryan', hora: '17:34', texto: 'Ah entendi. Então acho que esse relatório não tem essa coluna mesmo. Vou confirmar.' },
      { de: 'cliente', autor: 'Thiago', hora: '17:36', texto: 'Confirma quando? Preciso fechar comissão dos garçons.' },
      { de: 'atendente', autor: 'Ryan', hora: '17:42', texto: 'Até amanhã eu te respondo.' },
      { de: 'nota', autor: 'Sistema', hora: '17:42', texto: 'Terceira interação sobre o mesmo pedido. Nenhuma alternativa oferecida (ex.: relatório de Consumo por Área ou extração manual pelo suporte).' },
    ],
  },

  {
    id: 'TCK-1049',
    loja: 'Sushi Hana',
    contato: 'Paula Ferraz',
    atendente: 'murilo',
    canal: 'WhatsApp',
    assunto: 'Lista de espera: como avisar o cliente que a mesa liberou',
    tags: ['Reservas', 'Lista de espera'],
    abertoEm: '2026-08-04T19:20:00',
    primeiraRespostaMin: 8,
    duracaoMin: 33,
    contextoSugerido: 'rotina',
    mensagens: [
      { de: 'cliente', autor: 'Paula', hora: '19:20', texto: 'Oi! Estou com 11 pessoas na lista de espera aqui. Tem como o sistema avisar automático quando libera mesa ou eu tenho que ligar pra cada um?' },
      { de: 'atendente', autor: 'Murilo', hora: '19:28', texto: 'Oi Paula! Tem automático sim, e já está incluído no seu plano. Funciona assim: quando você libera a mesa no painel, o próximo da fila recebe WhatsApp na hora com um botão "Estou chegando" e um tempo de tolerância (padrão 10 min).' },
      { de: 'atendente', autor: 'Murilo', hora: '19:29', texto: 'Só que aqui na sua conta o disparo automático está desligado — está em modo manual, então hoje você precisa clicar em "Chamar" em cada pessoa. Quer que eu ligue o automático?' },
      { de: 'cliente', autor: 'Paula', hora: '19:31', texto: 'Quero! Mas o tempo de 10 min é pouco pra gente, o pessoal aqui espera na praça. Dá pra 15?' },
      { de: 'atendente', autor: 'Murilo', hora: '19:37', texto: 'Dá. Coloquei 15 min e liguei o disparo automático ✅ Testei com o primeiro da sua fila (Marcos, 2 pessoas) e a mensagem saiu.\n\nUma dica pra hoje: se alguém não responder no prazo, o sistema pula pro próximo mas NÃO remove a pessoa da fila — ela volta pro fim. Assim você não perde ninguém se a praça estiver cheia.' },
      { de: 'cliente', autor: 'Paula', hora: '19:44', texto: 'Ótimo, isso resolve. Obrigada!' },
      { de: 'atendente', autor: 'Murilo', hora: '19:53', texto: 'Boa noite de operação! Se a fila passar de 20 pessoas, me chama que eu te mostro o painel de tempo médio de espera — ajuda a dar previsão certa pro cliente.' },
    ],
  },

  {
    id: 'TCK-1048',
    loja: 'Trattoria Bianchi',
    contato: 'Giulia Bianchi',
    atendente: 'murilo',
    canal: 'Web',
    assunto: 'Não consegue adicionar usuário novo (limite do plano)',
    tags: ['Usuários', 'Plano'],
    abertoEm: '2026-08-04T11:12:00',
    primeiraRespostaMin: 14,
    duracaoMin: 52,
    contextoSugerido: 'financeiro',
    mensagens: [
      { de: 'cliente', autor: 'Giulia', hora: '11:12', texto: 'Estou tentando cadastrar a nova gerente e dá erro "limite de usuários atingido". Como aumento?' },
      { de: 'atendente', autor: 'Murilo', hora: '11:26', texto: 'Oi Giulia! Seu plano Essencial inclui 5 usuários e você tem 5 ativos. Antes de te oferecer upgrade, olhei a lista: dois usuários não acessam há mais de 90 dias — marcelo@ (último acesso 02/04) e cozinha02@ (28/03).\n\nSe algum desses dois não trabalha mais com vocês, dá pra desativar e liberar a vaga sem custo nenhum.' },
      { de: 'cliente', autor: 'Giulia', hora: '11:33', texto: 'O Marcelo saiu em abril mesmo. O cozinha02 é um login compartilhado que ninguém usa mais.' },
      { de: 'atendente', autor: 'Murilo', hora: '11:39', texto: 'Então libero os dois. Só um alerta antes: desativar não apaga o histórico, os pedidos e reservas que eles lançaram continuam no relatório. Pode desativar?' },
      { de: 'cliente', autor: 'Giulia', hora: '11:41', texto: 'Pode.' },
      { de: 'atendente', autor: 'Murilo', hora: '11:49', texto: 'Desativados ✅ Você tem 2 vagas livres agora. Já pode cadastrar a gerente em Usuários → Novo usuário.\n\nSugestão: cadastre ela como perfil Gerente (não Admin) — Gerente vê relatório e opera reservas, mas não altera plano nem exclui dados. Se depois precisar, você promove em 1 clique.' },
      { de: 'cliente', autor: 'Giulia', hora: '12:04', texto: 'Cadastrei, entrou de primeira. Obrigada por não me vender upgrade que eu não precisava 😄' },
    ],
  },

  {
    id: 'TCK-1047',
    loja: 'Café Mirante',
    contato: 'Sérgio Prado',
    atendente: 'vitoria',
    canal: 'WhatsApp',
    assunto: 'Cliente sumiu do produto há 40 dias (contato proativo)',
    tags: ['Churn', 'Proativo'],
    abertoEm: '2026-08-03T10:15:00',
    primeiraRespostaMin: 0,
    duracaoMin: 68,
    contextoSugerido: 'churn',
    mensagens: [
      { de: 'nota', autor: 'Sistema', hora: '10:15', texto: 'Alerta de saúde: nenhum acesso há 40 dias. Contato proativo iniciado pelo CS (não houve solicitação do cliente).' },
      { de: 'atendente', autor: 'Victoria', hora: '10:15', texto: 'Oi Sérgio, tudo bem? Aqui é a Victoria, da Dionísio. Vi que o Café Mirante não acessa o painel desde 24/06 e resolvi te chamar antes de virar cobrança sem uso. Aconteceu alguma coisa? Mudou a operação?' },
      { de: 'cliente', autor: 'Sérgio', hora: '10:41', texto: 'Oi Victoria. Olha, a gente basicamente parou de usar. Fechamos o café pra reforma em junho, reabrimos semana que vem. Estava até pensando em cancelar e assinar de novo depois.' },
      { de: 'atendente', autor: 'Victoria', hora: '10:47', texto: 'Faz total sentido não pagar cheio parado. Mas cancelar e voltar tem um custo escondido pra você: perde as configurações, o cardápio montado e o histórico de clientes — teria que refazer tudo na volta.\n\nAlternativa: pausa de assinatura. A conta congela por até 60 dias, você paga R$ 0, e tudo volta exatamente como está quando reabrir. Faz sentido pra você?' },
      { de: 'cliente', autor: 'Sérgio', hora: '10:58', texto: 'Não sabia que existia isso. Faz sentido sim, mas eu reabro dia 12 — então seria pausa de uma semana só?' },
      { de: 'atendente', autor: 'Victoria', hora: '11:04', texto: 'Nesse caso pausa nem vale a pena. O melhor pra você é outra coisa: eu lanço um crédito proporcional pelos dias de junho/julho que a loja ficou fechada (35 dias) — dá R$ 348 de crédito na próxima fatura. Isso já resolve o "paguei sem usar".\n\nE pra reabertura, eu te ajudo a preparar: revisar cardápio, conferir horários e ligar as reservas antes do dia 12.' },
      { de: 'cliente', autor: 'Sérgio', hora: '11:12', texto: 'Isso é ótimo. Bora fazer assim.' },
      { de: 'atendente', autor: 'Victoria', hora: '11:23', texto: 'Crédito de R$ 348 lançado ✅ Marquei uma call de 30 min pra sexta 15h pra revisar tudo pra reabertura (te mandei o convite). Qualquer coisa antes disso me chama por aqui. Boa reforma final! ☕' },
    ],
  },

  {
    id: 'TCK-1046',
    loja: 'Burger Lab',
    contato: 'Diego Antunes',
    atendente: 'vitoria',
    canal: 'Web',
    assunto: 'Cupom de desconto aplicando valor errado',
    tags: ['Pedidos', 'Cupom'],
    abertoEm: '2026-08-03T13:48:00',
    primeiraRespostaMin: 16,
    duracaoMin: 84,
    contextoSugerido: 'bug',
    mensagens: [
      { de: 'cliente', autor: 'Diego', hora: '13:48', texto: 'Criei o cupom LAB20 de 20% e ele está descontando 20 REAIS, não 20%. Já saíram 14 pedidos com desconto errado hoje.' },
      { de: 'atendente', autor: 'Victoria', hora: '14:04', texto: 'Oi Diego! Vou olhar o cupom agora antes de qualquer palpite.' },
      { de: 'atendente', autor: 'Victoria', hora: '14:11', texto: 'Confirmado o comportamento: o cupom LAB20 está cadastrado com tipo "Valor fixo" e valor 20, não como "Percentual". Por isso R$ 20 e não 20%.\n\nO campo de tipo fica logo acima do valor e vem como "Valor fixo" por padrão — é fácil passar batido, não foi falta de atenção sua.' },
      { de: 'cliente', autor: 'Diego', hora: '14:15', texto: 'Droga. E os 14 pedidos que já saíram?' },
      { de: 'atendente', autor: 'Victoria', hora: '14:22', texto: 'Levantei aqui: dos 14, em 9 o desconto de R$ 20 foi MENOR que os 20% (ticket alto) — nesses o cliente pagou mais do que devia, diferença total de R$ 63,40. Nos outros 5 foi maior, prejuízo pra você de R$ 41,10.\n\nCorrigi o cupom pra Percentual 20% e testei: pedido de R$ 120 agora desconta R$ 24 ✅' },
      { de: 'cliente', autor: 'Diego', hora: '14:29', texto: 'E o que eu faço com os 9 que pagaram mais?' },
      { de: 'atendente', autor: 'Victoria', hora: '14:38', texto: 'Sugestão: eu te mando a lista dos 9 (nome, pedido, diferença) e você decide. O caminho mais barato pra reputação costuma ser mandar um cupom de crédito do valor da diferença pra cada um — dá pra gerar em lote aqui, eu faço pra você.\n\nSe preferir estorno em dinheiro, também dá, mas passa pela adquirente e leva de 5 a 10 dias.' },
      { de: 'cliente', autor: 'Diego', hora: '14:44', texto: 'Faz o cupom de crédito em lote. E me manda a lista.' },
      { de: 'atendente', autor: 'Victoria', hora: '15:12', texto: 'Feito ✅ 9 cupons de crédito gerados e enviados (lista completa no seu e-mail). Aproveitei e conferi seus outros 3 cupons ativos: o VOLTA10 também está como valor fixo — quer que eu ajuste ou é intencional?' },
      { de: 'cliente', autor: 'Diego', hora: '15:16', texto: 'Esse é intencional, R$ 10 mesmo. Valeu por checar!' },
    ],
  },
];

/* --- Avaliações de demonstração (para o dashboard já nascer com dado) ---- */
const AVALIACOES_DEMO = [
  {
    id: 'AV-001', ticketId: 'TCK-1042', contexto: 'churn',
    notas: { entendeu: 5, resolveu: 5, precisao: 5, tom: 4 },
    observacoes: 'Referência de investigação: descartou a hipótese óbvia (antecedência) e achou a causa real (bloqueio de período). Fechou com prevenção + escalada pro gerente de conta. Usar como exemplo no treinamento.',
    avaliador: 'Murilo B.', avaliadoEm: '2026-08-04T09:20:00',
  },
  {
    id: 'AV-002', ticketId: 'TCK-1039', contexto: 'onboarding',
    notas: { entendeu: 5, resolveu: 5, precisao: 5, tom: 5 },
    observacoes: 'Explicou a diferença entre os três links em vez de só mandar um, e confirmou o entendimento antes de encerrar. Onboarding modelo.',
    avaliador: 'Murilo B.', avaliadoEm: '2026-08-04T10:05:00',
  },
  {
    id: 'AV-003', ticketId: 'TCK-1036', contexto: 'bug',
    notas: { entendeu: 2, resolveu: 4, precisao: 3, tom: 3 },
    observacoes: 'Dois chutes (cache e reinstalar) antes de olhar o log — o cliente precisou pedir duas vezes pra alguém investigar. A causa (webhook duplicado) foi bem resolvida, mas o caminho custou 1h de produção errada na cozinha. Faltou pedir desculpa pelo prejuízo.',
    avaliador: 'Murilo B.', avaliadoEm: '2026-07-29T14:10:00',
  },
  {
    id: 'AV-004', ticketId: 'TCK-1044', contexto: 'financeiro',
    notas: { entendeu: 5, resolveu: 5, precisao: 5, tom: 4 },
    observacoes: 'Conferiu a fatura antes de responder, citou política de reembolso com número e prazo, e preveniu recorrência restringindo módulos pagos ao admin. Excelente.',
    avaliador: 'Murilo B.', avaliadoEm: '2026-08-05T08:40:00',
  },
  {
    id: 'AV-005', ticketId: 'TCK-1030', contexto: 'irritado',
    notas: { entendeu: 5, resolveu: 4, precisao: 5, tom: 4 },
    observacoes: 'Primeira resposta levou 31 min num caso com cliente na porta — único ponto fraco. Depois disso, conduziu muito bem: assumiu a falha de produto, abriu report, procurou outras reservas presas e mandou material por escrito.',
    avaliador: 'Murilo B.', avaliadoEm: '2026-07-25T11:30:00',
  },
  {
    id: 'AV-006', ticketId: 'TCK-1027', contexto: 'bug',
    notas: { entendeu: 2, resolveu: 1, precisao: 2, tom: 3 },
    observacoes: 'Especulou fuso horário sem checar e o próprio cliente derrubou a hipótese. Prometeu chamado técnico e não abriu — ticket reaberto em 23/07. Divergência de R$ 2.630 em relatório financeiro é caso de escalar na hora.',
    avaliador: 'Murilo B.', avaliadoEm: '2026-07-24T16:05:00',
  },
  {
    id: 'AV-007', ticketId: 'TCK-1021', contexto: 'churn',
    notas: { entendeu: 5, resolveu: 5, precisao: 4, tom: 5 },
    observacoes: 'Save de churn exemplar: olhou uso antes de argumentar, apresentou downgrade e cancelamento com a mesma clareza e assumiu a falha do time em não ter agido antes.',
    avaliador: 'Murilo B.', avaliadoEm: '2026-07-18T09:15:00',
  },
  {
    id: 'AV-008', ticketId: 'TCK-1018', contexto: 'rotina',
    notas: { entendeu: 5, resolveu: 5, precisao: 5, tom: 4 },
    observacoes: 'Diagnóstico direto no template pendente, explicou o motivo da reprovação da Meta e validou com reserva de teste real antes de dizer que estava resolvido. Validar sempre assim.',
    avaliador: 'Murilo B.', avaliadoEm: '2026-07-15T10:50:00',
  },
];
